name: Validate Plugin

on:
  push:

jobs:
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ktlint check
        run: ./gradlew ktlintCheck

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: ./gradlew test
